Repository reactphp/promise, pull requests merged in 2018-04, with the labels that each got.

#112 Mark legacy progress support / notification API as deprecated
  README.md
  src/Deferred.php
  src/ExtendedPromiseInterface.php
  src/PromiseInterface.php
Labels: easy pick, maintenance

#113 Improve memory consumption by only passing resolver args to resolver and canceller if callback requires them
  src/Promise.php
  tests/PromiseTest.php
  tests/PromiseTest/CancelTestTrait.php
Labels: new feature

#114 Recommend rejecting promises by throwing an exception
  README.md
Labels: maintenance

#115 Improve memory consumption by using static progress callback without binding to promise
  src/Promise.php
  tests/PromiseTest.php
Labels: new feature
