Repository reactphp/promise, pull requests merged in 2019-05, with the labels that each got.

#138 Enforce Throwable rejection reason and require PHP 7+ as a consequence
  .travis.yml
  README.md
  composer.json
  src/Exception/CompositeException.php
  src/FulfilledPromise.php
  src/Internal/CancellationQueue.php
  src/Internal/Queue.php
  src/Promise.php
  src/RejectedPromise.php
  src/functions.php
  tests/FunctionRejectTest.php
  tests/FunctionalRejectTest.php
  tests/PromiseTest/RejectTestTrait.php
  tests/RejectedPromiseTest.php
Labels: BC break, easy pick, help wanted, maintenance

#140 Fix php-coveralls setup
  .travis.yml
Labels: maintenance

#141 Throwable type improvements
  src/Deferred.php
  src/Promise.php
  src/RejectedPromise.php
  src/functions.php
  tests/FunctionalRejectTest.php
Labels: BC break
