Repository reactphp/promise, pull requests merged in 2020-08, with the labels that each got.

#172 Add type declarations for `some()`
  src/functions.php
Labels: easy pick, maintenance

#177 Update PHPUnit configuration schema for PHPUnit 9.3 and minor clean up
  .gitattributes
  .gitignore
  .travis.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/TestCase.php
Labels: maintenance

#171 Initialize Deferred's state in the constructor
  src/Deferred.php
Labels: new feature

#178 Add full core team to the license
  LICENSE
  composer.json
Labels: maintenance
