Repository reactphp/promise, pull requests merged in 2022-02, with the labels that each got.

#195 Support intersection types (PHP 8.1+ / Promise v2)
  src/functions.php
  tests/FunctionCheckTypehintTest.php
  tests/fixtures/CallbackWithIntersectionTypehintClass.php
  tests/fixtures/CountableException.php
  tests/fixtures/CountableNonException.php
Labels: new feature

#209 Support intersection types (PHP 8.1+ / ported from v2 to v3)
  src/functions.php
  tests/FunctionCheckTypehintTest.php
  tests/fixtures/CallbackWithIntersectionTypehintClass.php
  tests/fixtures/CountableException.php
Labels: new feature

#210 Improve test suite to fix default Exception message (PHP 8.1)
  tests/Internal/RejectedPromiseTest.php
Labels: maintenance

#213 Require argument for `resolve()` function
  README.md
  src/Deferred.php
  src/Promise.php
  src/functions.php
  tests/FunctionAnyTest.php
  tests/FunctionRaceTest.php
  tests/FunctionSomeTest.php
  tests/PromiseTest/CancelTestTrait.php
  tests/PromiseTest/PromiseFulfilledTestTrait.php
  tests/PromiseTest/PromisePendingTestTrait.php
  tests/PromiseTest/PromiseRejectedTestTrait.php
  tests/PromiseTest/PromiseSettledTestTrait.php
  tests/PromiseTest/RejectTestTrait.php
Labels: new feature, BC break
