Repository reactphp/promise, pull requests merged in 2022-06, with the labels that each got.

#219 [RFC] Remove `some()`, `map()`, `reduce()` functions
  README.md
  src/functions.php
  tests/FunctionAnyTest.php
  tests/FunctionMapTest.php
  tests/FunctionReduceTest.php
  tests/FunctionSomeTest.php
Labels: BC break

#224 [RFC] Remove `done()` method
  README.md
  src/Internal/FulfilledPromise.php
  src/Internal/RejectedPromise.php
  src/Promise.php
  src/PromiseInterface.php
  src/functions.php
  tests/ErrorCollector.php
  tests/PromiseTest.php
  tests/PromiseTest/PromiseFulfilledTestTrait.php
  tests/PromiseTest/PromisePendingTestTrait.php
  tests/PromiseTest/PromiseRejectedTestTrait.php
  tests/PromiseTest/PromiseSettledTestTrait.php
  tests/PromiseTest/RejectTestTrait.php
  tests/PromiseTest/ResolveTestTrait.php
Labels: BC break

#225 Support `iterable` type for `all()` + `race()` + `any()`
  README.md
  src/functions.php
  tests/FunctionAllTest.php
  tests/FunctionAnyTest.php
  tests/FunctionRaceTest.php
Labels: new feature

#230 Update test suite to avoid deprecation notices for PHP 8.1+
  phpunit.xml.dist
  tests/Internal/RejectedPromiseTest.php
Labels: maintenance

#229 Continue internal `Queue` execution also after fiber is suspended
  src/Internal/Queue.php
  tests/Internal/QueueTest.php
  tests/PromiseTest/PromiseFulfilledTestTrait.php
Labels: new feature

#226 chore(docs): remove leading dollar sign
  README.md
Labels: maintenance
